### ISSUE TITLE
Update an item in a wishlist

### ISSUE THREAD

**Issue by worldwidewebbz** [sternie-devops-squad/wishlists#10]
**As a** user
**I need** update an item in a wishlist
**So that** I can make adjustments to item details

**Details & Assumptions:** 
* ...

**Acceptance Criteria:**

```gherkin
Given I have item foo in the wishlist with a quantity of 2
When I decrease the quantity by 1
Then I have a quantity of 1 of item foo in the wishlist
```

**Comment by sb8414** [comment]
@worldwidewebbz Hey man, my nosetests were failing. Can you help me debug?
