### ISSUE TITLE
Create a Cloud Foundry app in IBM Cloud

### ISSUE THREAD

**Issue by FeiHan-NYU** [sternie-devops-squad/wishlists#29]
**As a** developer
**I need** to use Platform as a Service for running the wishlist application
**So that** the wishlist application can access on-demand computing resources on the cloud

**Details & Assumptions:** 
* Team IBM Cloud Foundry Account is set up

**Acceptance Criteria:**

```gherkin
Given a running app instance
When visiting the app url in a browser
Then the app UI should be displayed on the webpage
```

**Comment by sternie** [comment]
Name of the app is nyu-wishlist-service-sp2201

**Comment by sternie** [comment]
![Screen Shot 2022-04-04 at 11.56.31 AM.png](https://images.zenhubusercontent.com/6215448533fc2b409e2ad320/b2237b7e-7cb6-44fa-9084-137120449090)

App is running with URL https://nyu-wishlist-service-sp2201.us-south.cf.appdomain.cloud/
