### ISSUE TITLE
Refactor Microservice to use Flask-RESTX & Swagger Docs

### ISSUE THREAD

**Issue by worldwidewebbz** [sternie-devops-squad/wishlists#33]
**As a** developer 
**I need** to refactor the existing microservice to use Flask-RESTX and Swagger Docs
**So that** my microservice benefits from the added support of the extension and has documentation describing the RESTful APIs

**Details & Assumptions:** 
* ...

**Acceptance Criteria:**

```gherkin
Given I have refactored the microservice to use Flask-RESTX and added Swagger Docs
When I run the tests and microservice
Then I get the same test coverage and the service starts up properly
```

**Comment by lpk229** [comment]
will be done in next sprint
