### ISSUE TITLE
Delete a wishlist

### ISSUE THREAD

**Issue by sb8414** [sternie-devops-squad/wishlists#5]
**As a** user
**I need** to delete a wishlist
**So that** I no longer have wishlists that I don't intend to use

**Details & Assumptions:** 

**Acceptance Criteria:**

```gherkin
Given I request to delete a wishlist
When I view my list of wishlists
Then I see that the wishlist is no longer there
```

**Comment by sternie** [comment]
@worldwidewebbz hey! I copied and pasted the reference code and made changes to reflect "wishlists". The one thing I cannot get right is the delete wishlist test in routes.py. I've scanned John's code and tried to find the discrepancy, but I cannot find it. Can you help?
