### ISSUE TITLE
Add UI Elements to Update a Wishlist

### ISSUE THREAD

**Issue by FeiHan-NYU** [sternie-devops-squad/wishlists#50]
**As a** user
**I need** to be able to update a wishlist via the web UI
**So that** I can make desired changes to the wishlist

**Details & Assumptions:** 
* Wishlist RESTful API services have been implemented

**Acceptance Criteria:**

```gherkin
Given Wishlist app instance is running on the cloud
When the user specifies an attribute change (e.g., the Wishlist name) to a Wishlist, and clicks on the "Update Wishlist" button
Then the wishlist should be updated to reflect the user-specified change
```

**Comment by worldwidewebbz** [comment]
In addition: 
- need help to review / update the code for adding wishlist items (when creating a wishlist)
- wishlist.created_date is currently handled in a very hacky way.. please help take a look at well, thanks!
