### ISSUE TITLE
Add Unit Test Job

### ISSUE THREAD

**Issue by sternie** [sternie-devops-squad/wishlists#74]
**As a** developer
**I need** a unit test job
**So that** I can run unit tests when I run the nosetests command

**Details & Assumptions:** 
* ...

**Acceptance Criteria:**

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by FeiHan-NYU** [comment]
Btw this story seems to be covered by #63 already?

**Comment by sternie** [comment]
We can close it. When I was looking at the requirements, I broke down every requirement into small chunks based on the instructions in the class presentations.
